import { useNavigate, useParams } from 'react-router-dom';
import { colors, fonts } from '@/tokens';

const CONTENT: Record<string, { title: string; body: string[] }> = {
  privacy: {
    title: 'Privacy Policy',
    body: [
      'Last updated: March 2026',
      'SoGoJet ("we", "our", "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and share information when you use our mobile application and website (collectively, the "Service").',
      'Information We Collect: We collect information you provide directly, such as your name, email address, and travel preferences when you create an account. We also collect usage data including search history, saved destinations, and interaction patterns to personalize your feed.',
      'How We Use Your Information: We use your information to provide and improve the Service, personalize your travel recommendations, send price alerts for saved destinations, and communicate with you about your account.',
      'Data Sharing: We do not sell your personal information. We may share data with flight and hotel partners solely to display pricing and availability. We use Appwrite for secure data storage and authentication.',
      'Data Security: We use industry-standard encryption and security measures to protect your data. All API communications are encrypted via HTTPS.',
      'Your Rights: You may request access to, correction of, or deletion of your personal data at any time by contacting support@sogojet.com.',
      'Contact Us: If you have questions about this Privacy Policy, please contact us at support@sogojet.com.',
    ],
  },
  terms: {
    title: 'Terms of Service',
    body: [
      'Last updated: March 2026',
      'Welcome to SoGoJet. By using our Service, you agree to these Terms of Service. Please read them carefully.',
      'Service Description: SoGoJet is a travel deal discovery platform that helps you find flights and hotels. We aggregate pricing data from multiple sources and provide AI-generated travel recommendations.',
      'Account Registration: You may browse as a guest or create an account. You are responsible for maintaining the security of your account credentials.',
      'Pricing Information: Flight and hotel prices displayed are sourced from third-party providers and may change at any time. SoGoJet does not guarantee the accuracy or availability of any displayed price. Final pricing is determined by the airline or hotel at the time of booking.',
      'AI-Generated Content: Trip plans and travel recommendations are generated by AI and are provided for informational purposes only. We recommend verifying all travel information independently.',
      'Acceptable Use: You agree not to misuse the Service, attempt to access it through automated means, or use it for any unlawful purpose.',
      'Limitation of Liability: SoGoJet is a discovery and recommendation platform. We are not a travel agency and do not process bookings directly. We are not liable for any issues arising from third-party bookings.',
      'Changes to Terms: We may update these Terms from time to time. Continued use of the Service constitutes acceptance of any changes.',
      'Contact: For questions about these Terms, contact support@sogojet.com.',
    ],
  },
};

export default function LegalScreen() {
  const navigate = useNavigate();
  const { type } = useParams<{ type: string }>();
  const content = CONTENT[type ?? ''] ?? CONTENT.privacy!;

  return (
    <div
      className="screen"
      style={{
        background: colors.duskSand,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'auto',
      }}
    >
      {/* Header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          paddingTop: 56,
          paddingBottom: 16,
          paddingInline: 20,
        }}
      >
        <button
          onClick={() => navigate(-1)}
          style={{ padding: 4 }}
        >
          <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={colors.deepDusk} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M19 12H5" />
            <path d="M12 19l-7-7 7-7" />
          </svg>
        </button>
        <h1
          style={{
            fontFamily: `"${fonts.display}", system-ui, sans-serif`,
            fontWeight: 800,
            fontSize: 22,
            lineHeight: '26px',
            letterSpacing: '-0.01em',
            textTransform: 'uppercase',
            color: colors.deepDusk,
            margin: 0,
          }}
        >
          {content.title}
        </h1>
      </div>

      {/* Content */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: 16,
          paddingInline: 24,
          paddingBottom: 40,
        }}
      >
        {content.body.map((paragraph, i) => (
          <p
            key={i}
            style={{
              fontFamily: `"${fonts.body}", system-ui, sans-serif`,
              fontSize: i === 0 ? 12 : 15,
              fontWeight: i === 0 ? 500 : 400,
              lineHeight: i === 0 ? '16px' : '24px',
              color: i === 0 ? colors.mutedText : colors.bodyText,
              margin: 0,
            }}
          >
            {paragraph}
          </p>
        ))}
      </div>
    </div>
  );
}
